version: '3'

networks:
  default:
    external: true
    name: local

services:
  mysql-db:
    image: mysql:8.0.31-debian
    hostname: mysql-db
    container_name: mysql-db
    ports:
      - 3306:3306
    networks:
      - default
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=user
    # volumes:
    #   - ./data/mysql/user:/var/lib/mysql
    #   - ./conf/mysql/conf.d:/etc/mysql/conf.d

  postgres-db:
    image: postgres:16.2-alpine3.19
    hostname: postgres-db
    container_name: postgres-db
    ports:
      - 5432:5432
    networks:
      - default
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=user
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data

  cache-redis:
    image: redis:6-alpine
    hostname: cache-redis
    # volumes:
    #   - ./data/redis/cache/:/data
    #   - ./conf/redis/cache/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - default
    command: ["redis-server"]
